language: node_js
node_js:
  - "8.1.4"
before_install:
  - npm install
  - npm rebuild wd
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
  - npm run test:eslint
  - npm run test:sauce
  - npm run build:cordova
notifications:
  email: true
sudo: false

addons:
  sauce_connect: true
